// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Copied from: https://github.com/Azure/azure-functions-language-worker-protobuf

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: identity/ClaimsIdentityRpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Light-weight representation of a .NET System.Security.Claims.ClaimsIdentity object.
// This is the same serialization as found in EasyAuth, and needs to be kept in sync with
// its ClaimsIdentitySlim definition, as seen in the WebJobs extension:
// https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.Http/ClaimsIdentitySlim.cs
type RpcClaimsIdentity struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AuthenticationType *NullableString        `protobuf:"bytes,1,opt,name=authentication_type,json=authenticationType,proto3" json:"authentication_type,omitempty"`
	NameClaimType      *NullableString        `protobuf:"bytes,2,opt,name=name_claim_type,json=nameClaimType,proto3" json:"name_claim_type,omitempty"`
	RoleClaimType      *NullableString        `protobuf:"bytes,3,opt,name=role_claim_type,json=roleClaimType,proto3" json:"role_claim_type,omitempty"`
	Claims             []*RpcClaim            `protobuf:"bytes,4,rep,name=claims,proto3" json:"claims,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RpcClaimsIdentity) Reset() {
	*x = RpcClaimsIdentity{}
	mi := &file_identity_ClaimsIdentityRpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcClaimsIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcClaimsIdentity) ProtoMessage() {}

func (x *RpcClaimsIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_identity_ClaimsIdentityRpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcClaimsIdentity.ProtoReflect.Descriptor instead.
func (*RpcClaimsIdentity) Descriptor() ([]byte, []int) {
	return file_identity_ClaimsIdentityRpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcClaimsIdentity) GetAuthenticationType() *NullableString {
	if x != nil {
		return x.AuthenticationType
	}
	return nil
}

func (x *RpcClaimsIdentity) GetNameClaimType() *NullableString {
	if x != nil {
		return x.NameClaimType
	}
	return nil
}

func (x *RpcClaimsIdentity) GetRoleClaimType() *NullableString {
	if x != nil {
		return x.RoleClaimType
	}
	return nil
}

func (x *RpcClaimsIdentity) GetClaims() []*RpcClaim {
	if x != nil {
		return x.Claims
	}
	return nil
}

// Light-weight representation of a .NET System.Security.Claims.Claim object.
// This is the same serialization as found in EasyAuth, and needs to be kept in sync with
// its ClaimSlim definition, as seen in the WebJobs extension:
// https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.Http/ClaimSlim.cs
type RpcClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcClaim) Reset() {
	*x = RpcClaim{}
	mi := &file_identity_ClaimsIdentityRpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcClaim) ProtoMessage() {}

func (x *RpcClaim) ProtoReflect() protoreflect.Message {
	mi := &file_identity_ClaimsIdentityRpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcClaim.ProtoReflect.Descriptor instead.
func (*RpcClaim) Descriptor() ([]byte, []int) {
	return file_identity_ClaimsIdentityRpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcClaim) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RpcClaim) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_identity_ClaimsIdentityRpc_proto protoreflect.FileDescriptor

const file_identity_ClaimsIdentityRpc_proto_rawDesc = "" +
	"\n" +
	" identity/ClaimsIdentityRpc.proto\x1a\x1ashared/NullableTypes.proto\"\xea\x01\n" +
	"\x11RpcClaimsIdentity\x12@\n" +
	"\x13authentication_type\x18\x01 \x01(\v2\x0f.NullableStringR\x12authenticationType\x127\n" +
	"\x0fname_claim_type\x18\x02 \x01(\v2\x0f.NullableStringR\rnameClaimType\x127\n" +
	"\x0frole_claim_type\x18\x03 \x01(\v2\x0f.NullableStringR\rroleClaimType\x12!\n" +
	"\x06claims\x18\x04 \x03(\v2\t.RpcClaimR\x06claims\"4\n" +
	"\bRpcClaim\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04typeBn\n" +
	"*com.microsoft.azure.functions.rpc.messagesZ@github.com/laveeshb/azure-functions-go-worker/internal/rpc/protob\x06proto3"

var (
	file_identity_ClaimsIdentityRpc_proto_rawDescOnce sync.Once
	file_identity_ClaimsIdentityRpc_proto_rawDescData []byte
)

func file_identity_ClaimsIdentityRpc_proto_rawDescGZIP() []byte {
	file_identity_ClaimsIdentityRpc_proto_rawDescOnce.Do(func() {
		file_identity_ClaimsIdentityRpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_ClaimsIdentityRpc_proto_rawDesc), len(file_identity_ClaimsIdentityRpc_proto_rawDesc)))
	})
	return file_identity_ClaimsIdentityRpc_proto_rawDescData
}

var file_identity_ClaimsIdentityRpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_identity_ClaimsIdentityRpc_proto_goTypes = []any{
	(*RpcClaimsIdentity)(nil), // 0: RpcClaimsIdentity
	(*RpcClaim)(nil),          // 1: RpcClaim
	(*NullableString)(nil),    // 2: NullableString
}
var file_identity_ClaimsIdentityRpc_proto_depIdxs = []int32{
	2, // 0: RpcClaimsIdentity.authentication_type:type_name -> NullableString
	2, // 1: RpcClaimsIdentity.name_claim_type:type_name -> NullableString
	2, // 2: RpcClaimsIdentity.role_claim_type:type_name -> NullableString
	1, // 3: RpcClaimsIdentity.claims:type_name -> RpcClaim
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_identity_ClaimsIdentityRpc_proto_init() }
func file_identity_ClaimsIdentityRpc_proto_init() {
	if File_identity_ClaimsIdentityRpc_proto != nil {
		return
	}
	file_shared_NullableTypes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_ClaimsIdentityRpc_proto_rawDesc), len(file_identity_ClaimsIdentityRpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_ClaimsIdentityRpc_proto_goTypes,
		DependencyIndexes: file_identity_ClaimsIdentityRpc_proto_depIdxs,
		MessageInfos:      file_identity_ClaimsIdentityRpc_proto_msgTypes,
	}.Build()
	File_identity_ClaimsIdentityRpc_proto = out.File
	file_identity_ClaimsIdentityRpc_proto_goTypes = nil
	file_identity_ClaimsIdentityRpc_proto_depIdxs = nil
}
