// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Copied from: https://github.com/Azure/azure-functions-language-worker-protobuf

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: FunctionRpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FunctionRpc_EventStream_FullMethodName = "/AzureFunctionsRpcMessages.FunctionRpc/EventStream"
)

// FunctionRpcClient is the client API for FunctionRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Interface exported by the server.
type FunctionRpcClient interface {
	EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamingMessage, StreamingMessage], error)
}

type functionRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewFunctionRpcClient(cc grpc.ClientConnInterface) FunctionRpcClient {
	return &functionRpcClient{cc}
}

func (c *functionRpcClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamingMessage, StreamingMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FunctionRpc_ServiceDesc.Streams[0], FunctionRpc_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamingMessage, StreamingMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FunctionRpc_EventStreamClient = grpc.BidiStreamingClient[StreamingMessage, StreamingMessage]

// FunctionRpcServer is the server API for FunctionRpc service.
// All implementations must embed UnimplementedFunctionRpcServer
// for forward compatibility.
//
// Interface exported by the server.
type FunctionRpcServer interface {
	EventStream(grpc.BidiStreamingServer[StreamingMessage, StreamingMessage]) error
	mustEmbedUnimplementedFunctionRpcServer()
}

// UnimplementedFunctionRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFunctionRpcServer struct{}

func (UnimplementedFunctionRpcServer) EventStream(grpc.BidiStreamingServer[StreamingMessage, StreamingMessage]) error {
	return status.Error(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedFunctionRpcServer) mustEmbedUnimplementedFunctionRpcServer() {}
func (UnimplementedFunctionRpcServer) testEmbeddedByValue()                     {}

// UnsafeFunctionRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FunctionRpcServer will
// result in compilation errors.
type UnsafeFunctionRpcServer interface {
	mustEmbedUnimplementedFunctionRpcServer()
}

func RegisterFunctionRpcServer(s grpc.ServiceRegistrar, srv FunctionRpcServer) {
	// If the following call panics, it indicates UnimplementedFunctionRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FunctionRpc_ServiceDesc, srv)
}

func _FunctionRpc_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FunctionRpcServer).EventStream(&grpc.GenericServerStream[StreamingMessage, StreamingMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FunctionRpc_EventStreamServer = grpc.BidiStreamingServer[StreamingMessage, StreamingMessage]

// FunctionRpc_ServiceDesc is the grpc.ServiceDesc for FunctionRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FunctionRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AzureFunctionsRpcMessages.FunctionRpc",
	HandlerType: (*FunctionRpcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _FunctionRpc_EventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "FunctionRpc.proto",
}
