// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Copied from: https://github.com/Azure/azure-functions-language-worker-protobuf

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shared/NullableTypes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullableString struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to String_:
	//
	//	*NullableString_Value
	String_       isNullableString_String_ `protobuf_oneof:"string"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableString) Reset() {
	*x = NullableString{}
	mi := &file_shared_NullableTypes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableString) ProtoMessage() {}

func (x *NullableString) ProtoReflect() protoreflect.Message {
	mi := &file_shared_NullableTypes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableString.ProtoReflect.Descriptor instead.
func (*NullableString) Descriptor() ([]byte, []int) {
	return file_shared_NullableTypes_proto_rawDescGZIP(), []int{0}
}

func (x *NullableString) GetString_() isNullableString_String_ {
	if x != nil {
		return x.String_
	}
	return nil
}

func (x *NullableString) GetValue() string {
	if x != nil {
		if x, ok := x.String_.(*NullableString_Value); ok {
			return x.Value
		}
	}
	return ""
}

type isNullableString_String_ interface {
	isNullableString_String_()
}

type NullableString_Value struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

func (*NullableString_Value) isNullableString_String_() {}

type NullableDouble struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Double:
	//
	//	*NullableDouble_Value
	Double        isNullableDouble_Double `protobuf_oneof:"double"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableDouble) Reset() {
	*x = NullableDouble{}
	mi := &file_shared_NullableTypes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableDouble) ProtoMessage() {}

func (x *NullableDouble) ProtoReflect() protoreflect.Message {
	mi := &file_shared_NullableTypes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableDouble.ProtoReflect.Descriptor instead.
func (*NullableDouble) Descriptor() ([]byte, []int) {
	return file_shared_NullableTypes_proto_rawDescGZIP(), []int{1}
}

func (x *NullableDouble) GetDouble() isNullableDouble_Double {
	if x != nil {
		return x.Double
	}
	return nil
}

func (x *NullableDouble) GetValue() float64 {
	if x != nil {
		if x, ok := x.Double.(*NullableDouble_Value); ok {
			return x.Value
		}
	}
	return 0
}

type isNullableDouble_Double interface {
	isNullableDouble_Double()
}

type NullableDouble_Value struct {
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3,oneof"`
}

func (*NullableDouble_Value) isNullableDouble_Double() {}

type NullableBool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Bool:
	//
	//	*NullableBool_Value
	Bool          isNullableBool_Bool `protobuf_oneof:"bool"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableBool) Reset() {
	*x = NullableBool{}
	mi := &file_shared_NullableTypes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableBool) ProtoMessage() {}

func (x *NullableBool) ProtoReflect() protoreflect.Message {
	mi := &file_shared_NullableTypes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableBool.ProtoReflect.Descriptor instead.
func (*NullableBool) Descriptor() ([]byte, []int) {
	return file_shared_NullableTypes_proto_rawDescGZIP(), []int{2}
}

func (x *NullableBool) GetBool() isNullableBool_Bool {
	if x != nil {
		return x.Bool
	}
	return nil
}

func (x *NullableBool) GetValue() bool {
	if x != nil {
		if x, ok := x.Bool.(*NullableBool_Value); ok {
			return x.Value
		}
	}
	return false
}

type isNullableBool_Bool interface {
	isNullableBool_Bool()
}

type NullableBool_Value struct {
	Value bool `protobuf:"varint,1,opt,name=value,proto3,oneof"`
}

func (*NullableBool_Value) isNullableBool_Bool() {}

type NullableTimestamp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Timestamp:
	//
	//	*NullableTimestamp_Value
	Timestamp     isNullableTimestamp_Timestamp `protobuf_oneof:"timestamp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableTimestamp) Reset() {
	*x = NullableTimestamp{}
	mi := &file_shared_NullableTypes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableTimestamp) ProtoMessage() {}

func (x *NullableTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_NullableTypes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableTimestamp.ProtoReflect.Descriptor instead.
func (*NullableTimestamp) Descriptor() ([]byte, []int) {
	return file_shared_NullableTypes_proto_rawDescGZIP(), []int{3}
}

func (x *NullableTimestamp) GetTimestamp() isNullableTimestamp_Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *NullableTimestamp) GetValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Timestamp.(*NullableTimestamp_Value); ok {
			return x.Value
		}
	}
	return nil
}

type isNullableTimestamp_Timestamp interface {
	isNullableTimestamp_Timestamp()
}

type NullableTimestamp_Value struct {
	Value *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

func (*NullableTimestamp_Value) isNullableTimestamp_Timestamp() {}

var File_shared_NullableTypes_proto protoreflect.FileDescriptor

const file_shared_NullableTypes_proto_rawDesc = "" +
	"\n" +
	"\x1ashared/NullableTypes.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\x0eNullableString\x12\x16\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05valueB\b\n" +
	"\x06string\"2\n" +
	"\x0eNullableDouble\x12\x16\n" +
	"\x05value\x18\x01 \x01(\x01H\x00R\x05valueB\b\n" +
	"\x06double\".\n" +
	"\fNullableBool\x12\x16\n" +
	"\x05value\x18\x01 \x01(\bH\x00R\x05valueB\x06\n" +
	"\x04bool\"T\n" +
	"\x11NullableTimestamp\x122\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05valueB\v\n" +
	"\ttimestampBk\n" +
	"*com.microsoft.azure.functions.rpc.messagesZ=github.com/Azure/azure-functions-go-worker/internal/rpc/protob\x06proto3"

var (
	file_shared_NullableTypes_proto_rawDescOnce sync.Once
	file_shared_NullableTypes_proto_rawDescData []byte
)

func file_shared_NullableTypes_proto_rawDescGZIP() []byte {
	file_shared_NullableTypes_proto_rawDescOnce.Do(func() {
		file_shared_NullableTypes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_NullableTypes_proto_rawDesc), len(file_shared_NullableTypes_proto_rawDesc)))
	})
	return file_shared_NullableTypes_proto_rawDescData
}

var file_shared_NullableTypes_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_NullableTypes_proto_goTypes = []any{
	(*NullableString)(nil),        // 0: NullableString
	(*NullableDouble)(nil),        // 1: NullableDouble
	(*NullableBool)(nil),          // 2: NullableBool
	(*NullableTimestamp)(nil),     // 3: NullableTimestamp
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_shared_NullableTypes_proto_depIdxs = []int32{
	4, // 0: NullableTimestamp.value:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_NullableTypes_proto_init() }
func file_shared_NullableTypes_proto_init() {
	if File_shared_NullableTypes_proto != nil {
		return
	}
	file_shared_NullableTypes_proto_msgTypes[0].OneofWrappers = []any{
		(*NullableString_Value)(nil),
	}
	file_shared_NullableTypes_proto_msgTypes[1].OneofWrappers = []any{
		(*NullableDouble_Value)(nil),
	}
	file_shared_NullableTypes_proto_msgTypes[2].OneofWrappers = []any{
		(*NullableBool_Value)(nil),
	}
	file_shared_NullableTypes_proto_msgTypes[3].OneofWrappers = []any{
		(*NullableTimestamp_Value)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_NullableTypes_proto_rawDesc), len(file_shared_NullableTypes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_NullableTypes_proto_goTypes,
		DependencyIndexes: file_shared_NullableTypes_proto_depIdxs,
		MessageInfos:      file_shared_NullableTypes_proto_msgTypes,
	}.Build()
	File_shared_NullableTypes_proto = out.File
	file_shared_NullableTypes_proto_goTypes = nil
	file_shared_NullableTypes_proto_depIdxs = nil
}
