// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Copied from: https://github.com/Azure/azure-functions-language-worker-protobuf

syntax = "proto3";

option java_package = "com.microsoft.azure.functions.rpc.messages";
option go_package = "github.com/laveeshb/azure-functions-go-worker/internal/rpc/proto";

import "google/protobuf/timestamp.proto";

message NullableString {
  oneof string {
    string value = 1;
  }
}

message NullableDouble {
  oneof double {
    double value = 1;
  }
}

message NullableBool {
  oneof bool {
    bool value = 1;
  }
}

message NullableTimestamp {
  oneof timestamp {
    google.protobuf.Timestamp value = 1;
  }
}
